# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = "Core Cache: the write-options record"
language = "other"
manifest_version = 3
name = "core-cache-write-options"
service_id = ""

[scripts]
  build = "cargo build --target wasm32-wasip2 && mkdir -p bin && cp target/wasm32-wasip2/debug/core_cache_write_options.wasm bin/main.wasm"
