# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = "Hello, world: exporting http-incoming by hand, no SDK"
language = "other"
manifest_version = 3
name = "hello-world-http-incoming"
service_id = ""

[local_server]

[scripts]
  build = """\
cargo build --target wasm32-wasip2 && \
mkdir -p bin && \
cp target/wasm32-wasip2/debug/hello_world_http_incoming.wasm bin/main.wasm\
"""
