# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = "Reading the request body by hand, no SDK"
language = "other"
manifest_version = 3
name = "reading-the-body"
service_id = ""

[local_server]

[scripts]
  build = "cargo build --target wasm32-wasip2 && mkdir -p bin && cp target/wasm32-wasip2/debug/reading_the_body.wasm bin/main.wasm"
