# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = "Headers: listing names, writing more than one value, removing, and status and version"
language = "other"
manifest_version = 3
name = "headers"
service_id = ""

[scripts]
  build = "cargo build --target wasm32-wasip2 && mkdir -p bin && cp target/wasm32-wasip2/debug/headers.wasm bin/main.wasm"
