# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = "The September 2026 compute.wit update: clone, and a cache lookup timeout through extra-cache-override-details"
language = "other"
manifest_version = 3
name = "compute-wit-update"
service_id = ""

[local_server]
  [local_server.backends.http_me]
    url = "https://http-me.fastly.dev"

[scripts]
  build = "cargo build --target wasm32-wasip2 && mkdir -p bin && cp target/wasm32-wasip2/debug/compute_wit_update.wasm bin/main.wasm"

[setup]
  [setup.backends.http_me]
    address = "http-me.fastly.dev"
    port = 443
