# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = "Core Cache: non-transactional insert and replace"
language = "other"
manifest_version = 3
name = "core-cache-insert-replace"
service_id = ""

[scripts]
  build = "cargo build --target wasm32-wasip2 && mkdir -p bin && cp target/wasm32-wasip2/debug/core_cache_insert_replace.wasm bin/main.wasm"
