# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = "Reading and writing a KV Store"
language = "other"
manifest_version = 3
name = "kv-store"
service_id = ""

[local_server.kv_stores]
  notes = []

[scripts]
  build = "cargo build --target wasm32-wasip2 && mkdir -p bin && cp target/wasm32-wasip2/debug/kv_store.wasm bin/main.wasm"
