# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = "Synthesizing a simple HTTP response by hand, no SDK"
language = "other"
manifest_version = 3
name = "synthesizing-a-response"
service_id = ""

[local_server]

[scripts]
  build = "cargo build --target wasm32-wasip2 && mkdir -p bin && cp target/wasm32-wasip2/debug/synthesizing_a_response.wasm bin/main.wasm"
