# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = "Reading from a Config Store"
language = "other"
manifest_version = 3
name = "config-store"
service_id = ""

[local_server]
  [local_server.config_stores.settings]
    format = "inline-toml"
  [local_server.config_stores.settings.contents]
    greeting = "Hello from the Config Store!"
    "site.name" = "Behind the Panic"

[scripts]
  build = "cargo build --target wasm32-wasip2 && mkdir -p bin && cp target/wasm32-wasip2/debug/config_store.wasm bin/main.wasm"
