# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
description = "Purging Core Cache objects by surrogate key"
language = "other"
manifest_version = 3
name = "surrogate-key-purging"
service_id = ""

[scripts]
  build = "cargo build --target wasm32-wasip2 && mkdir -p bin && cp target/wasm32-wasip2/debug/surrogate_key_purging.wasm bin/main.wasm"
